language: node_js
node_js:
  - "12.18.2"
script:
  - echo "Deploying"
#  - npm run test
#  - npm run coverage
  - npm run build
install:
  - npm install -g firebase-tools
after-success:
  - firebase deploy --token $FIREBASE_TOKEN
